version: "3.9"

services:
  tf-api:
    container_name: tf-api
    working_dir: /usr/src/app
    build: 
      context: .
      dockerfile: "./Dockerfile"
    env_file: 
      - "./.env.dev"
    ports:
      - "5003:5003"
    volumes:
      - app:/usr/src/app
      - node_modules:/app/node_modules
    depends_on:
      - "mongo"
    restart: on-failure
    networks:
      - tf-api
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo
    networks:
      - tf-api

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules
  app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./

networks:
  tf-api: