version: "3.9"

services:
  tf-api:
    container_name: tf-api
    working_dir: /app/
    build: 
      context: .
      dockerfile: "./Dockerfile"
    env_file: 
      - "./.env.dev"
    environment:
      - NODE_ENV=dev
      - MONGO_URI=${MONGO_URI}
      - DEBUG=${DEBUG}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_PROTOCOL=${MONGO_PROTOCOL}
      - SERVICE_TOKEN=${SERVICE_TOKEN}
      - AUTH_URL=${AUTH_URL}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - app:/app
      - node_modules:/app/node_modules
    depends_on:
      - "mongo"
    restart: on-failure
    networks:
      - tf-api
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo
    networks:
      - tf-api

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules
  app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./

networks:
  tf-api: