version: "3.9"

services:
  tf_api_test:
    container_name: tf_api_test
    working_dir: /usr/src/app
    build: 
      context: .
      dockerfile: "./Dockerfile"
    environment:
      - NODE_ENV=test
      - MONGO_URI=${MONGO_URI}
      - MONGO_URI_PARAMS=${MONGO_URI_PARAMS}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_PROTOCOL=${MONGO_PROTOCOL}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - tf_api_test:/usr/src/app
      - node_modules_test:/usr/src/app/node_modules
    depends_on:
      - "tf_api_test_db"
    restart: on-failure
    networks:
      - tf_api_test
  tf_api_test_db:
    image: mongo
    ports:
      - "27019:27017"
    container_name: tf_api_test_db
    restart: on-failure
    networks:
      - tf_api_test
volumes:
  node_modules_test:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules
  tf_api_test:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./

networks:
  tf_api_test:
    external:
      name: tf_api_test